# Generated by Django 4.2.6 on 2023-10-18 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_tickets'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='ticket',
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='tickets.tickets')),
            ],
        ),
    ]
