# Generated by Django 4.2.6 on 2023-10-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=40, unique=True)),
                ('slug', models.CharField(blank=True, max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('title', models.CharField(max_length=40, unique=True)),
                ('slug', models.CharField(blank=True, max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
