# Generated by Django 4.2.6 on 2023-10-23 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('place_class', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('all_places', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='flights/')),
                ('description', models.TextField()),
                ('where_from', models.CharField(max_length=40)),
                ('where_to', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('place', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('luggage', models.CharField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.category', verbose_name='Class')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.flight', verbose_name='Airline')),
            ],
        ),
    ]
